In [1]:
import pandas as pd
import numpy as np
from google.cloud import bigquery
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file("key.json") # lokalizacja pobranego klucza z punktu 1.4.

client = bigquery.Client(credentials=credentials, project=credentials.project_id)

In [2]:
query = """
SELECT *
FROM `bigquery-public-data.noaa_gsod.gsod2020`
    limit 10
"""

query_job = client.query(query)
query_result = query_job.result()
df = query_result.to_dataframe()

In [3]:
df

,stn,wban,date,year,mo,da,temp,count_temp,dewp,count_dewp,...,flag_min,prcp,flag_prcp,sndp,fog,rain_drizzle,snow_ice_pellets,hail,thunder,tornado_funnel_cloud
0,010070,99999,2020-12-27,2020,12,27,24.9,4,13.7,4,...,None,0.00,I,999.9,0,0,0,0,0,0
1,010070,99999,2020-12-05,2020,12,05,7.5,4,-3.2,4,...,None,0.00,I,999.9,0,0,0,0,0,0
2,010070,99999,2020-11-22,2020,11,22,26.0,4,19.9,4,...,None,0.00,I,999.9,0,0,0,0,0,0
3,010150,99999,2020-11-22,2020,11,22,37.5,4,33.8,4,...,None,0.00,I,999.9,0,0,0,0,0,0
4,010350,99999,2020-11-03,2020,11,03,37.0,4,9999.9,0,...,None,0.00,I,999.9,0,0,0,0,0,0
5,010370,99999,2020-12-09,2020,12,09,36.3,4,26.6,4,...,None,0.00,I,999.9,0,0,0,0,0,0
6,010430,99999,2020-03-30,2020,03,30,26.2,4,9999.9,0,...,None,0.00,I,999.9,0,0,0,0,0,0
7,010460,99999,2020-12-27,2020,12,27,14.9,4,4.5,4,...,*,99.99,None,999.9,0,0,1,0,0,0
8,010470,99999,2020-08-19,2020,08,19,55.8,4,48.6,4,...,*,0.00,E,999.9,0,1,0,0,0,0
9,010680,99999,2020-03-15,2020,03,15,26.1,4,10.4,4,...,*,0.17,G,32.3,0,0,0,0,0,0

# Misja dodatkowa 3

### 3.1. Sprawdź, ile jest zapisanych wierszy z danymi.

In [4]:
query3_1 = """
select count(*) as count_rows from(
    SELECT  *
    FROM `bigquery-public-data.noaa_gsod.gsod2020`
    UNION ALL
    SELECT * FROM `bigquery-public-data.noaa_gsod.gsod2021`)
"""

df_3_1 = client.query(query3_1).to_dataframe()
df_3_1['count_rows'].loc[0]

np.int64(8145755)

### 3.2. Sprawdź, ile krajów jest uwzględnionych w danych.

In [5]:
query3_2 = """
        SELECT COUNT(DISTINCT country) as country_count
        FROM `bigquery-public-data.noaa_gsod.gsod2020` AS gsod
                 INNER JOIN `bigquery-public-data.noaa_gsod.stations` AS st
                            ON st.usaf = gsod.stn and gsod.wban = st.wban
        """

df_3_2= client.query(query3_2).to_dataframe()
df_3_2['country_count'].loc[0]

np.int64(236)

### 3.3. Sprawdź, w jaki sposób zapisywane są dzienne informacje dla poszczególnych lokalizacji.

In [6]:
query = """
SELECT *
FROM `bigquery-public-data.noaa_gsod.gsod2020`
    limit 10
"""

query_job = client.query(query)
query_result = query_job.result()
df = query_result.to_dataframe()
df

,stn,wban,date,year,mo,da,temp,count_temp,dewp,count_dewp,...,flag_min,prcp,flag_prcp,sndp,fog,rain_drizzle,snow_ice_pellets,hail,thunder,tornado_funnel_cloud
0,010070,99999,2020-12-27,2020,12,27,24.9,4,13.7,4,...,None,0.00,I,999.9,0,0,0,0,0,0
1,010070,99999,2020-12-05,2020,12,05,7.5,4,-3.2,4,...,None,0.00,I,999.9,0,0,0,0,0,0
2,010070,99999,2020-11-22,2020,11,22,26.0,4,19.9,4,...,None,0.00,I,999.9,0,0,0,0,0,0
3,010150,99999,2020-11-22,2020,11,22,37.5,4,33.8,4,...,None,0.00,I,999.9,0,0,0,0,0,0
4,010350,99999,2020-11-03,2020,11,03,37.0,4,9999.9,0,...,None,0.00,I,999.9,0,0,0,0,0,0
5,010370,99999,2020-12-09,2020,12,09,36.3,4,26.6,4,...,None,0.00,I,999.9,0,0,0,0,0,0
6,010430,99999,2020-03-30,2020,03,30,26.2,4,9999.9,0,...,None,0.00,I,999.9,0,0,0,0,0,0
7,010460,99999,2020-12-27,2020,12,27,14.9,4,4.5,4,...,*,99.99,None,999.9,0,0,1,0,0,0
8,010470,99999,2020-08-19,2020,08,19,55.8,4,48.6,4,...,*,0.00,E,999.9,0,1,0,0,0,0
9,010680,99999,2020-03-15,2020,03,15,26.1,4,10.4,4,...,*,0.17,G,32.3,0,0,0,0,0,0

 0.   stn - numer identyfikacyjny stacji
 1.   wban - numer Weather Bureau Air Force Navy, używany historycznie przez amerykańskie biura pogodowe oraz wojsko
 2.   date - data obserwacji
 3.   year - rok obserwacji
 4.   mo   - miesiąc obserwacji
 5.   da   - dzień obserwacji
 6.   temp - średnia temperatura dobowa w stopniach Fahrenheita, zaokrąglona do części dziesiętnych *
 7.   count_temp  - liczba obserwacji
 8.   dewp - średni, dobowy punkt rosy w stopniach Fahrenheita, zaokrąglony do części dziesiętnych *
 9.   count_dewp  - liczba obserwacji
 10.  slp - średnie ciśnienie nad poziomem morza (mbar), zaokrąglone do części dziesiętnych *
 11.  count_slp - liczba obserwacji
 12.  stp - średnie ciśnienie na poziomie stacji pogodowej (mbar), zaokrąglone do części dziesiętnych *
 13.  count_stp - liczba obserwacji
 14.  visib - średnia widoczność w milach, zaokrąglona do części dziesiętnych **
 15.  count_visib   - liczba obserwacji
 16.  wdsp - średnia predkość wiatru w węzłach, zaokrąglona do części dziesiętnych **
 17.  count_wdsp   - liczba obserwacji
 18.  mxpsd - maksymalna, utrzymująca się prędkość wiatru w węzłach, zaokrąglona do części dziesiętnych **
 19.  gust - maksymalna prędkość podmuchu wiatru w węzłach, zaokrąglona do części dziesiętnych **
 20.  max - maksymalna temperatura zarejestrowana dla danego kraju i regionu w stopniach Fahrenheita, zaokrąglona do części dziesiętnych *
 21.  flag_max - wskaźnik informujący czy maksymalna temperatura została pobrana z raportu, czy wyliczona z danych godzinowych
 22.  min - minimalna temperatura zarejestrowana dla danego kraju i regionu w stopniach Fahrenheita, zaokrąglona do części dziesiętnych *
 23.  flag_min - wskaźnik informujący czy maksymalna temperatura została pobrana z raportu, czy wyliczona z danych godzinowych
 24.  prcp - całkowita suma opadów (również roztopiony śnieg) w calach i setnych częściach milimetra ***
 25.  flag_prcp - wskaźnik informujący ilości raportów zgłoszonych w ciągu dnia
 - A - 1 raport 6-godzinnej ilości opadów
 - B - suma 2 raportów 6-godzinnych
 - C - suma 3 raportów 6-godzinnych
 - D - suma 4 raportów 6-godzinnych
 - E - 1 raport o 12-godzinnej ilości opadów
 - F - suma 2 raportów 12-godzinnych
 - G - 1 raport o 24-godzinnej ilości opadów
 26.  sndp - grbość pokrywy śnieżnej w calach, ostatni pomiar w ciągu dnia, jeżeli wykonano więcej niż 1 **
 27.  fog - wskaźnik informujący o występowaniu mgły w ciągu dnia
 28.  rain_drizzle - wskaźnik informujący o występowaniu mżawki w ciągu dnia
 29.  snow_ice_pellets - wskaźnik informujący o występowaniu krup śnieżnych bądź lodowych (mieszanka śniegu i lodu) w ciągu dnia
 30.  hail - wskaźnik informujący o występowaniu gradu w ciągu dnia
 31.  thunder - wskaźnik informujący o wystąpieniu burzy w ciągu dnia
 32.  tornado_funnel_cloud - wskaźnik informujący o wystąpieniu tornada bądź leja kondensacyjnego w ciągu dnia

\* brakujące wartości są zastąpione przez 9999.9
\** brakujące wartości są zastąpione przez 999.9
\*** brakujące wartości są zastąpione przez 99.99

### 3.4. Sprawdź, w jaki sposób zapisywane są wartości liczbowe.

wartości pomiarów zapisywane są w postaci liczb zmiennoprzecinkowych (float) zaokrąglone do pierwszego miejsca po przecinku, natomiast wartości opisyjące liczbe pomiarów są liczbami całkowitymi (integer)

### 3.5. Sprawdź, jaki przedział czasowy jest uwzględniony w danych. Dodatkowo porównaj zakresy czasowe dla różnych zmiennych pogodowych, takich jak temperatura i opady.

### 3.6. Sprawdź więcej informacji (co najmniej 5 różnych) o danych pogodowych. W tym celu nie wykonuj żadnych dodatkowych obliczeń. Wyniki przedstaw w formie krótkiego raportu.

# Część 4

### Przeanalizuj poniższe przypadki. Zastanów się, jakie dane potrzebujesz do każdego z nich, a następnie zapisz je w osobnych, jak najprostszych obiektach DataFrame. Na tym etapie nie wykonuj analiz ani obliczeń statystycznych. Wykonaj jedynie podstawowe uporządkowanie danych: wybierz potrzebne kolumny, zadbaj o poprawne typy danych (np. data), usuń duplikaty oraz jednoznacznie oznacz brakujące wartości. Gotowe dane z obiektów DataFrame zapisz w osobnych plikach CSV.

### 4.1. Chcemy posiadać podstawowe informacje o lokalizacjach pomiarów pogodowych (stacje) oraz krajach, tak aby dane były zrozumiałe dla człowieka i możliwe do dalszego przetwarzania.

In [7]:
query = """
        SELECT usaf, wban, name, country, lat, lon, elev
        FROM `bigquery-public-data.noaa_gsod.stations`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df = df.drop_duplicates()
df.to_csv('data/zad4_1.csv', index=False)
df

,usaf,wban,name,country,lat,lon,elev
0,007018,None,WXPOD 7018,None,0.000,0.000,+7018.0
1,007026,None,WXPOD 7026,AF,0.000,0.000,+7026.0
2,007070,None,WXPOD 7070,AF,0.000,0.000,+7070.0
3,008268,None,WXPOD8278,AF,32.950,65.567,+1156.7
4,008307,None,WXPOD 8318,AF,0.000,0.000,+8318.0
...,...,...,...,...,...,...,...
29585,A06884,00416,LURAY CAVERNS AIRPORT,US,38.667,-78.501,+0275.2
29586,A07086,00468,CARL R KELLER FIELD AIRPORT,US,41.516,-82.869,+0179.8
29587,A51255,00445,DEMOPOLIS MUNICIPAL AIRPORT,US,32.464,-87.954,+0034.1
29588,A51256,00451,BRANSON WEST MUNICIPAL EMERSO,US,36.699,-93.402,+0411.2
29589,723629,53998,ORANGE COUNTY AIRPORT,US,30.069,-93.804,+0004.0

### 4.2. Chcemy wygenerować podstawowe zestawienia dotyczące warunków pogodowych na świecie (np. temperatura, opady, wiatr) w ujęciu dziennym.

In [8]:
query = """
        SELECT stn, wban, temp, dewp, slp, stp, visib, wdsp, prcp, sndp, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['temp'] = df['temp'].replace(9999.9, None).astype(np.float64)
df['dewp'] = df['dewp'].replace(9999.9, None).astype(np.float64)
df['slp'] = df['slp'].replace(9999.9, None).astype(np.float64)
df['stp'] = df['stp'].replace(9999.9, None).astype(np.float64)
df['visib'] = df['visib'].replace(999.9, None).astype(np.float64)
df['wdsp'] = df['wdsp'].replace('999.9', None).astype(np.float64)
df['prcp'] = df['prcp'].replace(99.99, None).astype(np.float64)
df['sndp'] = df['sndp'].replace(999.9, None).astype(np.float64)
df = df.drop_duplicates()

df.to_csv('data/zad4_2.csv', index=False)
df

,stn,wban,temp,dewp,slp,stp,visib,wdsp,prcp,sndp,date
0,010430,None,32.1,NaN,NaN,999.9,NaN,7.3,0.00,NaN,2020-12-01
1,010980,None,35.4,34.6,989.2,987.4,NaN,12.9,0.43,NaN,2020-05-11
2,012210,None,32.2,26.7,NaN,999.9,NaN,NaN,0.12,NaN,2020-01-09
3,012420,None,28.7,27.8,NaN,999.9,NaN,NaN,0.00,NaN,2020-11-28
4,013520,None,14.3,NaN,NaN,999.9,NaN,NaN,0.01,48.0,2020-01-30
...,...,...,...,...,...,...,...,...,...,...,...
4119200,A51255,00445,32.3,19.6,NaN,29.1,9.6,2.4,0.00,NaN,2020-01-21
4119201,A51255,00445,59.6,54.5,NaN,5.7,8.2,0.0,NaN,NaN,2020-02-25
4119202,A51255,00445,56.5,51.1,NaN,20.7,7.3,2.8,NaN,NaN,2020-03-22
4119203,A51255,00445,64.7,57.7,NaN,22.1,7.6,5.6,NaN,NaN,2020-03-10
4119204,A51256,00451,61.5,49.2,NaN,970.5,10.0,3.0,0.00,NaN,2020-10-06

### 4.3. Chcemy poznać zjawiska ekstremalne w danych pogodowych poprzez uwypuklenie skrajnych wartości (np. bardzo wysokie/niskie temperatury, intensywne opady, silny wiatr).

In [9]:
query = """
        SELECT stn, wban, mxpsd, gust, max, min, prcp, snow_ice_pellets, hail, thunder, tornado_funnel_cloud, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['mxpsd'] = df['mxpsd'].replace('999.9', None).astype(np.float64)
df['gust'] = df['gust'].replace(999.9, None).astype(np.float64)
df['prcp'] = df['prcp'].replace(99.99, None).astype(np.float64)
df['snow_ice_pellets'] = df['snow_ice_pellets'].astype(np.int32).astype(np.bool)
df['hail'] = df['hail'].astype(np.int32).astype(np.bool)
df['thunder'] = df['thunder'].astype(np.int32).astype(np.bool)
df['tornado_funnel_cloud'] = df['tornado_funnel_cloud'].astype(np.int32).astype(np.bool)
df = df.drop_duplicates()

df.to_csv('data/zad4_3.csv', index=False)
df

,stn,wban,mxpsd,gust,max,min,prcp,snow_ice_pellets,hail,thunder,tornado_funnel_cloud,date
0,010070,None,9.1,13.6,43.7,42.1,0.0,False,False,False,False,2020-09-11
1,010350,None,NaN,NaN,43.5,40.5,0.0,False,False,False,False,2020-10-10
2,010470,None,13.6,NaN,53.8,48.9,0.0,False,False,False,False,2020-06-07
3,010980,None,24.7,33.4,39.7,36.3,0.0,False,False,False,False,2020-11-05
4,011440,None,28.7,38.7,47.7,38.8,0.0,False,False,False,False,2020-11-07
...,...,...,...,...,...,...,...,...,...,...,...,...
4119200,A51256,00451,14.0,22.9,73.4,41.0,0.0,False,False,False,False,2020-04-20
4119201,A51256,00451,9.9,20.0,91.4,75.2,NaN,False,False,False,False,2020-07-21
4119202,A51256,00451,15.0,28.0,55.4,24.8,NaN,False,False,True,False,2020-01-11
4119203,A51256,00451,8.9,NaN,42.8,37.4,0.0,False,False,False,False,2020-03-15
4119204,A51256,00451,12.0,20.0,64.4,46.4,0.0,False,False,False,False,2020-10-04

### 4.4. Chcemy przygotować dane umożliwiające analizę zmian warunków pogodowych w czasie (np. dla wybranych lokalizacji lub zmiennych).

In [10]:
query = """
        SELECT stn, wban, temp, dewp, stp, visib, wdsp, prcp, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['temp'] = df['temp'].replace(9999.9, None).astype(np.float64)
df['dewp'] = df['dewp'].replace(9999.9, None).astype(np.float64)
df['stp'] = df['stp'].replace(9999.9, None).astype(np.float64)
df['visib'] = df['visib'].replace(999.9, None).astype(np.float64)
df['wdsp'] = df['wdsp'].replace('999.9', None).astype(np.float64)
df['prcp'] = df['prcp'].replace(99.99, None).astype(np.float64)
df = df.drop_duplicates()

df.to_csv('data/zad4_4.csv', index=False)
df

            stn   wban  temp  dewp    stp  visib  wdsp  prcp        date
0        012620   None  28.4   NaN  999.9    NaN  28.2  0.00  2020-03-13
1        012620   None  55.3   NaN  999.9    NaN  17.3  0.00  2020-09-28
2        013500   None  32.3  28.5  882.2    NaN   9.1  0.00  2020-11-08
3        024960   None  40.3   NaN  999.9    6.2  12.6  0.00  2020-03-02
4        024960   None  41.3   NaN  999.9    7.8  35.5  0.01  2020-12-27
...         ...    ...   ...   ...    ...    ...   ...   ...         ...
4119200  999999  53974  61.6   NaN  999.9    NaN   NaN  0.02  2020-09-12
4119201  999999  73801  64.0   NaN  999.9    NaN   NaN  0.00  2020-11-15
4119202  999999  92826  84.2   NaN  999.9    NaN   NaN  0.00  2020-08-16
4119203  A00021  63884  39.8  32.2  962.7   10.0   NaN  0.00  2020-11-24
4119204  A00021  63884  45.7  40.8  955.7    8.9   NaN   NaN  2020-02-18

[4119205 rows x 9 columns]

### 4.5. Zdefiniuj własny dodatkowy przypadek związany z danymi pogodowymi.

#### Dane opisujące zjawiska pogodowe wpływające na poruszanie się samochodem

In [11]:
query = """
        SELECT stn, wban, visib, wdsp, mxpsd, gust, fog, hail, thunder, tornado_funnel_cloud, `date`
        FROM `bigquery-public-data.noaa_gsod.gsod2020`
        """

df = client.query(query).to_dataframe()
df['wban'] = df['wban'].replace('99999', None)
df['visib'] = df['visib'].replace(999.9, None).astype(np.float64)
df['wdsp'] = df['wdsp'].replace('999.9', None).astype(np.float64)
df['mxpsd'] = df['mxpsd'].replace('999.9', None).astype(np.float64)
df['gust'] = df['gust'].replace(999.99, None).astype(np.float64)

df['fog'] = df['fog'].astype(np.int32).astype(np.bool)
df['hail'] = df['hail'].astype(np.int32).astype(np.bool)
df['thunder'] = df['thunder'].astype(np.int32).astype(np.bool)
df['tornado_funnel_cloud'] = df['tornado_funnel_cloud'].astype(np.int32).astype(np.bool)
df = df.drop_duplicates()

df.to_csv('data/zad4_5.csv', index=False)
df

,stn,wban,visib,wdsp,mxpsd,gust,fog,hail,thunder,tornado_funnel_cloud,date
0,010580,None,NaN,9.9,11.1,27.2,False,False,False,False,2020-11-30
1,011330,None,NaN,4.7,6.2,11.3,False,False,False,False,2020-12-22
2,011980,None,NaN,NaN,NaN,999.9,False,False,False,False,2020-09-02
3,012120,None,NaN,39.4,47.0,59.4,False,False,False,False,2020-09-21
4,012900,None,6.2,4.5,6.0,999.9,True,False,False,False,2020-10-31
...,...,...,...,...,...,...,...,...,...,...,...
4119200,A51256,00451,10.0,9.8,14.0,22.0,False,False,False,False,2020-02-09
4119201,A51256,00451,10.0,5.1,9.9,15.0,False,False,False,False,2020-10-05
4119202,A51256,00451,10.0,2.9,7.0,999.9,False,False,False,False,2020-06-15
4119203,A51256,00451,9.3,4.2,9.9,17.1,False,False,False,False,2020-08-03
4119204,A51256,00451,9.9,5.2,13.0,19.0,False,False,False,False,2020-03-07

## Część 5

### Połącz ze sobą wszystkie dane otrzymane w części 4. Na ich podstawie utwórz jeden spójny zbiór danych i zapisz go jako oddzielny obiekt DataFrame. Jeżeli uznasz, że zasadne jest utworzenie więcej niż jednego zbioru, wykonaj to i uzasadnij swoją decyzję. Zadbaj o spójność struktury danych, w szczególności zgodność nazw kolumn, poprawność typów danych, brak duplikatów, jednoznaczne oznaczenie brakujących wartości. Wynik zapisz w pliku lub plikach CSV.

In [13]:
stations = pd.read_csv('data/zad4_1.csv')
pd.read_csv('data/zad4_2.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/daily_weather.csv', index=False)

pd.read_csv('data/zad4_3.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/extreme_weather.csv', index=False)

pd.read_csv('data/zad4_4.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/change_weather.csv', index=False)

pd.read_csv('data/zad4_5.csv').merge(stations, how='inner', left_on=['stn', 'wban'], right_on=['usaf', 'wban']).drop(columns=['usaf'])\
    .to_csv('data/car_weather.csv', index=False)

## Część 6

### Połącz ze sobą dane otrzymane w części 5 oraz dane znajdujące się w dodatkowym pliku CSV zawierającym informacje o produkcji rolniczej.
Wybierz jedno z poniższych źródeł danych:

### 6.1  Dane FAOSTAT (zalecane)

Dane dotyczące produkcji rolniczej dostępne w bazie FAOSTAT: https://www.fao.org/faostat/en/#data/QCL

Dane obejmują m.in.:

Area – nazwa kraju

Item – rodzaj uprawy

Year – rok

Element – typ wartości (np. Production, Yield)

Value – wartość

In [14]:
faostat = pd.read_csv('data/FAOSTAT_data_en_3-17-2026.csv').drop(columns=['Domain Code', 'Domain', 'Note'])
faostat

,Area Code (ISO2),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,AF,Afghanistan,5312,Area harvested,01371,"Almonds, in shell",2020,2020,ha,22134.00,A,Official figure
1,AF,Afghanistan,5412,Yield,01371,"Almonds, in shell",2020,2020,kg/ha,1775.90,A,Official figure
2,AF,Afghanistan,5510,Production,01371,"Almonds, in shell",2020,2020,t,39307.00,A,Official figure
3,AF,Afghanistan,5312,Area harvested,01654,"Anise, badian, coriander, cumin, caraway, fenn...",2020,2020,ha,25558.00,E,Estimated value
4,AF,Afghanistan,5412,Yield,01654,"Anise, badian, coriander, cumin, caraway, fenn...",2020,2020,kg/ha,703.00,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...
44914,ZW,Zimbabwe,5412,Yield,0111,Wheat,2020,2020,kg/ha,4779.60,A,Official figure
44915,ZW,Zimbabwe,5510,Production,0111,Wheat,2020,2020,t,212530.00,A,Official figure
44916,ZW,Zimbabwe,5510,Production,22211,Whole milk powder,2020,2020,t,5667.65,I,Value imputed by a receiving agency
44917,ZW,Zimbabwe,5510,Production,22222.01,"Whole milk, condensed",2020,2020,t,726.62,I,Value imputed by a receiving agency
44918,ZW,Zimbabwe,5510,Production,22221.01,"Whole milk, evaporated",2020,2020,t,4795.70,I,Value imputed by a receiving agency

In [ ]:
pd.read_csv('data/daily_weather.csv').merge(faostat, 'inner', left_on='country', right_on='Area Code (ISO2)')\
    .to_csv('data/daily_weather_fao.csv', index=False)

C:\Users\dorot\AppData\Local\Temp\ipykernel_19644\2562330920.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('data/daily_weather.csv').merge(faostat, 'inner', left_on='country', right_on='Area Code (ISO2)')\

In [ ]:
pd.read_csv('data/extreme_weather.csv').merge(faostat, 'inner', left_on='country', right_on='Area Code (ISO2)')\
    .to_csv('data/extreme_weather_fao.csv', index=False)